# Generated by Django 6.0.2 on 2026-02-11 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
