# Generated by Django 6.0.2 on 2026-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_dietplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthmetric',
            name='metric_type',
            field=models.CharField(choices=[('bp', 'Blood Pressure'), ('hr', 'Heart Rate'), ('temp', 'Body Temperature'), ('spo2', 'SpO2 Level'), ('sleep', 'Sleep Duration'), ('steps', 'Step Count')], max_length=10),
        ),
    ]
